name: akaunting-dev
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: akaunting-dev-router
    environment:
      - TS_AUTHKEY=${CLIENT_SECRET}
      - TS_ROUTES=172.15.5.0/24
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --snat-subnet-routes=true #--dnat-subnet-routes=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./tailscale_state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
    networks:
      tailscale_net:
        ipv4_address: 172.15.5.4

  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    build:
      context: .
    volumes:
      - ./akaunting_data:/var/www/html
    restart: unless-stopped
    env_file:
      - akaunting.run.env
    environment:
      - AKAUNTING_SETUP
    depends_on:
      - akaunting_db
    networks:
      akaunting_net:
      tailscale_net:
        ipv4_address: 172.15.5.5

  akaunting_db:
    container_name: akaunting-db
    image: mariadb
    volumes:
      - ./akaunting_db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - akaunting.db.env
    networks:
      akaunting_net:

# volumes:
#   akaunting_data:
#   akaunting_db:

networks:
  akaunting_net:
  tailscale_net:
    ipam:
      config:
        - subnet: 172.15.5.0/24
